runtime: nodejs10
service: node


handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /
  static_dir: build

env_variables:
  SQL_USER:
  SQL_PASSWORD:
  SQL_DATABASE:
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: 