create table User (
  id integer not null auto_increment,
  name varchar(30) default "",
  resource varchar(50) default "",
  resourceThumb varchar(50) default "",
  sex varchar(9) default "",
  birthday timestamp default CURRENT_TIMESTAMP,
  birthdayForDisplay varchar(5) default "",
  residence varchar(30) default "",
  annualIncome integer default 0,
  isMarried boolean,
  numberOfAdults integer default 0,
  numberOfMinors integer default 0,
  comment text,
  point integer default 0,
  insertTimestamp timestamp default CURRENT_TIMESTAMP,
  insertUser varchar(72) default "",
  updateTimestamp timestamp default CURRENT_TIMESTAMP,
  updateUser varchar(72) default "",
PRIMARY KEY(id));